[phases.setup]
nixPkgs = ["bun"]

[phases.install]
cmds = ["cd ../shared && bun install && cd ../backend && bun install"]

[phases.build]
cmds = [
  "cd ../shared && bun run build",
  "cd ../frontend && bun install && bun run build",
  "bun run build",
]

[start]
cmd = "bun start"
